### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Chay-HyunminPark** [RayanAlim/Toronto_Crime_Rate_Exploration#1]
**00-simulate_data.R**
`simulate_data <- function(num_records = 158) {
  
  data <- tibble(
    AREA_NAME_id = 1:num_records,
    HOOD_ID = sample(100:999, num_records, replace = TRUE),
    POPULATION_2023 = sample(1000:50000, num_records, replace = TRUE),
  )
  
  for(year in 2014:2023) {
    for(crime in c("ASSAULT", "AUTOTHEFT", "BIKETHEFT", "BREAKENTER", "HOMICIDE", "ROBBERY", "SHOOTING", "THEFTFROMMV", "THEFTOVER")) {
      data[[paste(crime, year, sep = "_")]] <- sample(0:100, num_records, replace = TRUE)
      data[[paste(crime, "RATE", year, sep = "_")]] <- runif(num_records, 0, 1000)
    }
  }
  
  return(data)
}`

> _Function Design_
The simulate_data function is well-structured. However, consider adding a docstring or comments inside the function to explain its purpose, input parameters, and the structure of the generated dataset.

> _Variable Naming_
The variable names are clear and follow a consistent style, which is good. However, consider making them more descriptive if needed.

**01-download_data.R**
`# get package
package <- show_package("neighbourhood-crime-rates")
package

# get all resources for this package
resources <- list_package_resources("neighbourhood-crime-rates")

# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))

# load the first datastore resource as a sample
raw_data <- filter(datastore_resources, row_number()==1) %>% get_resource()
raw_data`

> _Package Function Usage_
The usage of show_package, list_package_resources, and get_resource is appropriate. However, it would be beneficial to include comments explaining what each step does to enhance readability.

> _Session Info_
Consider including session information using sessionInfo() to enhance reproducibility.

**02-data_cleaning.R**
`cleaned_data <-
  raw_data |>
  janitor::clean_names() |>
  select(wing_width_mm, wing_length_mm, flying_time_sec_first_timer) |>
  filter(wing_width_mm != "caw") |>
  mutate(
    flying_time_sec_first_timer = if_else(flying_time_sec_first_timer == "1,35",
                                   "1.35",
                                   flying_time_sec_first_timer)
  ) |>
  mutate(wing_width_mm = if_else(wing_width_mm == "490",
                                 "49",
                                 wing_width_mm)) |>
  mutate(wing_width_mm = if_else(wing_width_mm == "6",
                                 "60",
                                 wing_width_mm)) |>
  mutate(
    wing_width_mm = as.numeric(wing_width_mm),
    wing_length_mm = as.numeric(wing_length_mm),
    flying_time_sec_first_timer = as.numeric(flying_time_sec_first_timer)
  ) |>
  rename(flying_time = flying_time_sec_first_timer,
         width = wing_width_mm,
         length = wing_length_mm
         ) |> 
  tidyr::drop_na()`

> _Comments and Documentation_
The purpose, author, date, and contact information in the preamble need to be updated with the correct information.
Add more detailed comments to explain the reasoning behind specific cleaning steps. This can be helpful for someone reading the script to understand why certain transformations are performed.

> _Data Cleaning_
The cleaning process is straightforward and effective. However, for better readability, consider breaking down the cleaning steps into separate lines, especially if a single line becomes too long. This makes it easier to understand and maintain.
`cleaned_data <- raw_data %>%
  janitor::clean_names() %>%
  select(wing_width_mm, wing_length_mm, flying_time_sec_first_timer) %>%
  filter(wing_width_mm != "caw") %>%
  mutate(
    flying_time_sec_first_timer = if_else(flying_time_sec_first_timer == "1,35", "1.35", flying_time_sec_first_timer),
    wing_width_mm = if_else(wing_width_mm %in% c("490", "6"), c("49", "60"), wing_width_mm)
  ) %>%
  mutate(
    wing_width_mm = as.numeric(wing_width_mm),
    wing_length_mm = as.numeric(wing_length_mm),
    flying_time_sec_first_timer = as.numeric(flying_time_sec_first_timer)
  ) %>%
  rename(flying_time = flying_time_sec_first_timer, width = wing_width_mm, length = wing_length_mm) %>%
  tidyr::drop_na()
`

> _Column Renaming_
The renaming of columns is clear, but ensure that the new column names are descriptive and intuitive. In the rename function, consider using names that convey the meaning of the variables.

**03-test_data.R**
`#### Preamble ####
# Purpose: Tests... [...UPDATE THIS...]
# Author: Rohan Alexander [...UPDATE THIS...]
# Date: 11 February 2023 [...UPDATE THIS...]
# Contact: rohan.alexander@utoronto.ca [...UPDATE THIS...]
# License: MIT
# Pre-requisites: [...UPDATE THIS...]
# Any other information needed? [...UPDATE THIS...]

#### Workspace setup ####
library(tidyverse)
# [...UPDATE THIS...]

#### Test data ####`

> Unfortunately, it seems that the code for testing the data is missing in your provided script

**04-model.R**

> Script for modeling appears to be concise and well-organized.

> _Model Output Directory_
Consider creating an output directory for storing the model files. This ensures that the model output is organized and easily accessible
`# Create output directory if it doesn't exist
if (!dir.exists("outputs/models")) dir.create("outputs/models")
`

**Comment by RayanAlim** [comment]
Addressed, thank you
